Update autostart
Added support for variable FTC Server IP and Port

diff --git a/autostart b/autostart
--- a/autostart
+++ b/autostart
@@ -146,15 +146,33 @@ if [ -z "$FTCEVENTSERVER_IP" ] ; then
 fi
 
 # Check if the provided FTC Server is online! If not write an error to the screen and exit!
-# RMW 10DEC23 - Added check for FTCServer on Port 8080 as well since it automatically picks that sometimes.
-if [ $(nc -z -w3 $FTCEVENTSERVER_IP 80; echo $?) -ne 0 ] || [ $(nc -z -w3 $FTCEVENTSERVER_IP 8080; echo $?) -ne 0 ]; then
-    echo "ERROR: FTC Server ${FTCEVENTSERVER_IP} is NOT online! Please check if the IP is correct or if the server is online/accessible." | adddate >> /home/pi/RPIKiosk.log
-    sed -i -e 's/\(<ERRORCODE>\).*\(<\/ERRORCODE>\)/<ERRORCODE>FTC Server '"${FTCEVENTSERVER_IP}"' is NOT online! Please check if the IP is correct or if the server is online\/accessible.<\/ERRORCODE>/g' /home/pi/error.html
-    KIOSKURL="file:///home/pi/error.html"
-    chromium-browser --disable-infobars --kiosk "$KIOSKURL"
-    exit 1;
+#If the FTC Event Server IP Contians a Colon we are passing a IP and Port
+if [[ "$FTCEVENTSERVER_IP" == *":"* ]]; then
+    #FTCEVENTSERVER_IP_OBJ=(${FTCEVENTSERVER_IP//;/ })
+    IFS=':' read -r -a arrIN <<< "$FTCEVENTSERVER_IP"
+    
+    # RMW 10DEC23 - Check the specific IP and Port we were provided
+    if [ $(nc -z -w3 ${arrIN[0]} ${arrIN[1]}; echo $?) -ne 0 ]; then
+        echo "ERROR: FTC Server ${FTCEVENTSERVER_IP} is NOT online! Please check if the IP is correct or if the server is online/accessible." | adddate >> /home/pi/RPIKiosk.log
+        sed -i -e 's/\(<ERRORCODE>\).*\(<\/ERRORCODE>\)/<ERRORCODE>FTC Server '"${FTCEVENTSERVER_IP}"' is NOT online! Please check if the IP is correct or if the server is online\/accessible.<\/ERRORCODE>/g' /home/pi/error.html
+        KIOSKURL="file:///home/pi/error.html"
+        chromium-browser --disable-infobars --kiosk "$KIOSKURL"
+        exit 1;
+    else
+        echo "DEBUG: FTC Server ${FTCEVENTSERVER_IP} is online!" | adddate >> /home/pi/RPIKiosk.log
+    fi
 else
-    echo "DEBUG: FTC Server ${FTCEVENTSERVER_IP} is online!" | adddate >> /home/pi/RPIKiosk.log
+    #Otherwise we just have an IP
+    # RMW 10DEC23 - Added check for FTCServer on Port 8080 as well since it automatically picks that sometimes.
+    if [ $(nc -z -w3 $FTCEVENTSERVER_IP 80; echo $?) -ne 0 ] || [ $(nc -z -w3 $FTCEVENTSERVER_IP 8080; echo $?) -ne 0 ]; then
+        echo "ERROR: FTC Server ${FTCEVENTSERVER_IP} is NOT online! Please check if the IP is correct or if the server is online/accessible." | adddate >> /home/pi/RPIKiosk.log
+        sed -i -e 's/\(<ERRORCODE>\).*\(<\/ERRORCODE>\)/<ERRORCODE>FTC Server '"${FTCEVENTSERVER_IP}"' is NOT online! Please check if the IP is correct or if the server is online\/accessible.<\/ERRORCODE>/g' /home/pi/error.html
+        KIOSKURL="file:///home/pi/error.html"
+        chromium-browser --disable-infobars --kiosk "$KIOSKURL"
+        exit 1;
+    else
+        echo "DEBUG: FTC Server ${FTCEVENTSERVER_IP} is online!" | adddate >> /home/pi/RPIKiosk.log
+    fi
 fi
 
 if [ -z "$FTCEVENTSERVER_EVENTCODE" ] ; then
